logoFile="assets/linnetts_caves/textures/logo_of_lc.png"

modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="0.1" #mandatory

displayName="Linett's Caves" #mandatory

authors="Linnett, Misty, The tired guy and other" #optional

description="Linnett’s Caves is a forge mod for Minecraft 1.20.1 that adds 5 new cave biomes to the Overworld. These cave biomes are exceedingly rare - yet they all contain a variety of unique blocks, items, mobs and mechanics that makes them considerable subterranean destinations. These five biomes are the Dessert Lair, the Garbage Dump, the Tea Pothole, the Solar Pit and the Mechanical Grottoes. To find any of these cave biomes, you’ll need to find villager cave finder. From him, you can buy a cave compass and a Linnetts Cave book guide book for Linnett’s Caves that should provide you with all the knowledge needed to find and explore any biome added by the mod. For more information on getting started, see the Getting Started on the mod’s discord wiki.  Linnetts Caves is a very large mod, with a great deal of effort put into the look and feel of each new biome. Each biome added may have its own ambient particles, fog, brightness and more. Because of this, it is recommended to experience this mod without shaders (Custom shaders will appear in the future, but this is not certain), since many shaders can alter or worsen the unique appearance of several of the biomes. The mod also has built-in compatibility with Just Enough Items."

[[dependencies."${mod_id}"]] #optional

   modId="forge" #mandatory

   mandatory=true #mandatory

   versionRange="${forge_version_range}" #mandatory

   ordering="NONE"

   side="BOTH"# Here's another dependency
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true

   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
